name: Run delete_invalid_custom_domains.sh

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # This sets the workflow to run at midnight (00:00) every Sunday

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: AZ CLI login
      uses: azure/login@v2
      with:
        client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
        tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
        allow-no-subscriptions: true

    - name: Run delete_invalid_custom_domains.sh
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        chmod +x ./delete_invalid_custom_domains.sh
        ./delete_invalid_custom_domains.sh
